/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Presenter.ALoginManagerPresenter;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author olf
 */
public class UserManager extends javax.swing.JFrame implements ILoginManager {

    ALoginManagerPresenter _Presenter;
    /**
     * Creates new form UserManager
     */
    public UserManager() {
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        addUserName_TextField = new javax.swing.JLabel();
        addUserPassword_Label = new javax.swing.JLabel();
        userName_TextField = new javax.swing.JTextField();
        userPassword_PasswordField = new javax.swing.JPasswordField();
        addUser_Button = new javax.swing.JButton();
        deleteUser_Button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        user_List = new javax.swing.JList();
        userList_Label = new javax.swing.JLabel();
        status_TextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UserManager");
        setName("UserManager"); // NOI18N
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("UserManager");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        addUserName_TextField.setText("Username:");

        addUserPassword_Label.setText("Password");

        addUser_Button.setText("add User");
        addUser_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUser_ButtonActionPerformed(evt);
            }
        });

        deleteUser_Button.setText("delete User");
        deleteUser_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteUser_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addUserName_TextField)
                            .addComponent(addUserPassword_Label))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userPassword_PasswordField)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(userName_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteUser_Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addUser_Button)))
                .addGap(139, 139, 139))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addUserName_TextField)
                    .addComponent(userName_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addUserPassword_Label)
                    .addComponent(userPassword_PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addUser_Button)
                    .addComponent(deleteUser_Button))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        user_List.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setViewportView(user_List);

        userList_Label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        userList_Label.setText("UserList:");

        status_TextField.setEditable(false);
        status_TextField.setText("status");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(status_TextField)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userList_Label)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(userList_Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(status_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deleteUser_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteUser_ButtonActionPerformed
        _Presenter.removeUser();
    }//GEN-LAST:event_deleteUser_ButtonActionPerformed

    private void addUser_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUser_ButtonActionPerformed
        _Presenter.saveUser();
    }//GEN-LAST:event_addUser_ButtonActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addUserName_TextField;
    private javax.swing.JLabel addUserPassword_Label;
    private javax.swing.JButton addUser_Button;
    private javax.swing.JButton deleteUser_Button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField status_TextField;
    private javax.swing.JLabel userList_Label;
    private javax.swing.JTextField userName_TextField;
    private javax.swing.JPasswordField userPassword_PasswordField;
    private javax.swing.JList user_List;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getUserName() {
       return this.userName_TextField.getText(); 
    }

    @Override
    public String getUserPassword() {
        return this.userPassword_PasswordField.getText();
       
    }

    
    public void setUserNames() {
       
    }

    @Override
    public void notifyUser(boolean logedIn, String notification) {
       String outputString = notification + " ";
       
       if (logedIn)
           outputString += "done!";
       else
           outputString += "failed!";   
        this.status_TextField.setText(outputString);
    }

    @Override
    public void setLoginManagerPresenter(ALoginManagerPresenter _InputPresenter) {
        this._Presenter = _InputPresenter;
    }

    @Override
    public void setUserNames(ArrayList<String> userNames) {
        this.user_List.clearSelection();
        DefaultListModel model = new DefaultListModel();
        for (String user: userNames) 
            model.addElement(user);
        user_List.setModel(model);                  
    }
}
