/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.event.ChangeListener;

/**
 *
 * @author olf
 */
public class SpinnerWalletView extends javax.swing.JFrame implements IWalletView {

    /**
     * Creates new form SpinnerWalletView
     */
    public SpinnerWalletView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        walletValue_Spinner = new javax.swing.JSpinner();
        walletValue_Label = new javax.swing.JLabel();
        header_Label = new javax.swing.JLabel();
        walletValue_ProgressBar = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SpinnerWallet");
        setResizable(false);

        walletValue_Label.setText("set to value:");

        header_Label.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        header_Label.setText("Wallet");

        jLabel1.setText("€");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(walletValue_ProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(header_Label))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(walletValue_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(walletValue_Spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(walletValue_Spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(walletValue_Label)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(walletValue_ProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel header_Label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel walletValue_Label;
    private javax.swing.JProgressBar walletValue_ProgressBar;
    private javax.swing.JSpinner walletValue_Spinner;
    // End of variables declaration//GEN-END:variables

    @Override
    public int getMoneyFromView(){
        return (int) this.walletValue_Spinner.getValue();
    }

    @Override
    public void setMoneyToView(double inputMoney) {
        this.walletValue_ProgressBar.setValue((int) inputMoney);
        this.walletValue_Spinner.setValue((int) inputMoney);
        
    }

    /*
     *@brief set Listener for changes in Model
     */
    @Override
    public void setMoneyListener(ChangeListener e_ref) {
        this.walletValue_Spinner.addChangeListener(e_ref);
    }

}
